# master部署模式，单节点single or 高可用模式cluster
architecture: "cluster"

# 工作目录，playbook运行过程中产生的文件存放到该位置，绝对路径，最后不能带/
workdir: '/opt'

# kubeadm引导集群所需镜像的repo，默认k8s.gcr.io.  registry.aliyuncs.com/google_containers为gcr的阿里镜像源
imageRepository: 'registry.aliyuncs.com/google_containers'
#imageRepository: 'k8s.gcr.io'

# 数据目录。会将docker，containerd，etcd，kubelet的数据目录配置到该目录下。绝对路径，最后不能带/
data_root: '/var/lib'
#data_root: '/data'


#容器运行时，docker or containerd
runtime: docker

# docker的版本，以下为参考值，建议18.09.0之后的版本，阿里源已不再提供18版本
# ubuntu 22.04系统该参数不生效，默认安装20版本
docker_version: '19.03.15'


# --------------containerd------------------
#TODO containerd版本选择
#containerd_version: ""

# sandbox镜像版本
sandbox_image_version: '3.5'
# ------------------------------------------

# kubectl,kubeadm,kubelet版本，应该与集群版本一致
#k8s_tools_version: '1.19.15'
k8s_tools_version: '1.21.14'

# k8s集群版本，参考：https://github.com/kubernetes/kubernetes/tree/master/CHANGELOG
#k8s_version: 'v1.19.15'
k8s_version: 'v1.21.14'

# 集群名称
clusterName: 'kubernetes'

# 集群网络配置，注意避开节点网络
service_cidr: '10.101.0.0/16'
pod_cidr: '172.19.0.0/16'
cluster_domain: 'cluster.local'
# kube-proxy模式. iptables或者ipvs
kube_proxy_mode: 'ipvs'

#-------------------lb----------------------
# 高可用vip，如果部署单Master，该项留空
#vip: ''
vip: '10.12.1.200'

# lb机器内网网卡名称，用于keepalived，如果部署单Master，该项忽略。如果各lb的网卡名称不一致，则将该变量在hosts文件各自定义。
# ansible all -m shell -a 'ip a'
nic: 'ens160'
#nic: 'eth0'

# keepalived virtual_router_id
virtual_router_id: 51
#------------------------------------------

# chrony服务器
chrony_server: "k8s-master1"

# 插件
# 是否安装calico
calico_enable: "true"
calico_mode: "ipip"   # ipip or vxlan

# 是否安装ingress-nginx，依赖于helm
ingress_enable: "true"

# 是否安装mtrics-server
metrics_enable: "true"

# 是否安装helm
helm_enable: "true"

# 是否启用etcd定期备份
etcd_backup_enable: "true"