---

- name: 0.系统初始化
  gather_facts: true
  hosts:
    - master
    - node
  roles:
    - 00-common
  tags: common

- name: 1.配置高可用
  gather_facts: true
  hosts:
    - lb
  roles:
    - { role: 01-ha, when: "architecture == 'cluster'" }
  tags: ha

- name: 2.集群初始化
  gather_facts: false
  hosts: k8s-master1
  roles:
    - 02-init
  tags: init

- name: 3.节点加入集群
  gather_facts: false
  hosts:
    - master
    - node
  serial: 1
  roles:
    - 03-node
  tags: node

- name: 4.部署集群组件
  gather_facts: false
  hosts: k8s-master1
  roles:
    - 04-addons
  tags: addons
