---
- name: 0.系统初始化
  gather_facts: true
  hosts: newnode 
  roles:
    - 00-common
  tags: common 

- name: 1.生成node添加脚本
  gather_facts: false
  hosts: k8s-master1
  roles:
    - 05-newnode

- name: 2.节点加入集群
  gather_facts: false
  hosts:
    - newnode
  serial: 1
  roles:
    - 05-newnode
  tags: newnode
